export const GET_POSTS_LIST_START = "GET_POSTS_LIST_START";
export const GET_POSTS_LIST_FAIL = "GET_POSTS_LIST_FAIL";
export const GET_POSTS_LIST_SUCCESS = "GET_POSTS_LIST_SUCCESS";
export const SET_POSTS_COPY = "SET_POSTS_COPY";

export const GET_POST_COMMENTS_START = "GET_POST_COMMENTS_START";
export const GET_POST_COMMENTS_SUCCESS = "GET_POST_COMMENTS_SUCCESS";
export const GET_POST_COMMENTS_FAIL = "GET_POST_COMMENTS_FAIL";
